name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted  # This makes it run on my Pi!
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies and build
      run: |
        npm install
        npm run build
        
    - name: Reload web server
      run: |
        sudo systemctl reload nginx