name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies and build
      run: |
        npm install
        npm run build
        
    - name: Copy built files to web directory
      run: |
        # Remove old files and copy new ones (no sudo needed)
        rm -rf /home/nmerck1/LivePortfolioWebsite/my-portfolio/dist/*
        cp -r dist/* /home/nmerck1/LivePortfolioWebsite/my-portfolio/dist/
        
    - name: Reload web server
      run: |
        sudo systemctl reload nginx